# Generated by Django 5.2.8 on 2025-11-19 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_dish_taste_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='dish',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='dish1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_dish', to='food.dish'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='dish2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondary_dish', to='food.dish'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='dish3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='third_dish', to='food.dish'),
        ),
    ]
