# Generated by Django 5.2.8 on 2025-11-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_remove_restaurant_dish_restaurant_dish1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
