# Generated by Django 5.2.8 on 2025-11-19 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_dish_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='image',
            new_name='image_url',
        ),
    ]
