# Generated by Django 5.2.8 on 2025-11-20 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_restaurant_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='user_name',
        ),
    ]
