# Generated by Django 5.2.8 on 2025-11-20 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_remove_feedback_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
